### ISSUE TITLE
Numpy.dtype Size change

### ISSUE THREAD

**Issue by christianhwa** [mpariente/pystoi#11]
Is this the expected error message when I run the function with 16,000 Hz wav files, as opposed to 10kHz? 

RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88

**Comment by christianhwa** [comment]
Sorry, I forgot to mention this as well... when I run the example code on the READEME with python 3.7 I get no module named 'utils'. I tried it with python 2.7 and got the error message above. Thanks!

**Comment by christianhwa** [comment]
My bad... I used pip to install it. In stoi.py, instead of 'import utils', I changed it to 'from pystoi import utils'- that managed to fix everything. 

Comparing my results to stoi.m run in matlab on the same files at 16,000 Hz, I'm getting 0.7035 in Matlab and 0.6997 in Python.

**Comment by mpariente** [comment]
I'll update the package on pip, so it's easy to install. 
Regarding the difference between the Matlab and python values, that's a relative difference of approximately 0.5%, I think it's reasonable. Thanks for your comments!

**Comment by mpariente** [comment]
Installation is now available with `pip install pystoi`
