### ISSUE TITLE
Is there any difference in Resample() between Matlab and Octave?

### ISSUE THREAD

**Issue by NearLinHere** [mpariente/pystoi#14]
This code is really helpful for my study. Thank you for this awesome work! There is no issue I am going to raise. Just some questions about MATLAB and Octave. 

The sample rate of my audio is 16000. According to the README file, the test will fail if I use python to do the resample. My question is how about the resample() function between MATLAB and Octave? Are they equivalent? It will be very appreciated if someone could answer this.

**Comment by mpariente** [comment]
I'm sorry but I also don't have Matlab anymore. 
@gauss256 was the one who included tests with Octave, maybe he could answer your questions.
I'm not an expert in resampling but it is a complex subject and there are several choices to make. I wouldn't be surprised that Matlab's and Octave's implementations are different, but they are both completely correct.

By the way, the tests will fail if we keep a `1e-6` absolute and relative tolerance but the results will still be very similar.

**Comment by gauss256** [comment]
I do not have MATLAB to compare the differences between its resample function and the one in Octave.

There is no one perfect way to resample, there are design choices to be made. Equally good implementations can give slightly different results. I expect that MATLAB and Octave have such minor differences, but they should not have much impact.

**Comment by NearLinHere** [comment]
@mpariente @gauss256 Thank you for answer this question!

After reading your answers, can I say that although MATLAB and Octave might have different resample algorithms, their results should be similar. However, the difference in algorithm design between python and MATLAB did impact the results. Am I right?

**Comment by mpariente** [comment]
I wouldn't say that. 
I'm sure that the small resampling differences between Octave and MATLAB would impact the results similarly. 
The resampling of Python is also correct but enough different that tests with absolute and relative tolerances of `1e-6` will fail. I expect the same behaviour with Octave. 
But none of this is a problem, the STOI results will still be consistent between the three languages..

**Comment by mpariente** [comment]
Feel free to reopen if needed.
Thanks @gauss256 for answering  !
