### ISSUE TITLE
Extended version

### ISSUE THREAD

**Issue by Rikorose** [mpariente/pystoi#16]
Hi,

are you sure that the if clause at [#L69](https://github.com/mpariente/pystoi/blob/master/pystoi/stoi.py#L69) is correct. I would expect the extended version to be the one in the else clause using the normalized segments.

**Comment by mpariente** [comment]
Hi, 

Thanks for your interest in `pystoi`.
The normalization actually happens in a [dedicated function](https://github.com/mpariente/pystoi/blob/master/pystoi/utils.py#L151) for the extended version. 

Both `stoi` and `estoi` are unit tested against the original implementations in Matlab. You can find the unit tests [here](https://github.com/mpariente/pystoi/blob/master/tests/test_stoi.py) for MATLAB and [here](https://github.com/mpariente/pystoi/blob/master/tests/test_stoi_octave.py) for the Octave version.

Hopes this clears your doubts,

**Comment by Rikorose** [comment]
Ok thanks, I might look into it if I have time next week
