### ISSUE TITLE
Is resampling really required?

### ISSUE THREAD

**Issue by anujstam** [mpariente/pystoi#22]
Hi,
The original paper (http://cas.et.tudelft.nl/pubs/Taal2010.pdf) mentions in the start of section 2 that the metric is supposed to be used on audio at a sampling rate of 10000 Hz. Is this really necessary? I get fairly similar results regardless of whether or not I resample my audio.

Thanks!

**Comment by mpariente** [comment]
Do you change the parameters to have the same length of intermediate intelligibility? And same OBM etc.. Or just omit the resampling? 
We _could_ add an option to avoid the resampling, but I wouldn't make this default. This is not my metric, I cannot decide this. 

Maybe @chtaal has something to answer to that?

**Comment by haoheliu** [comment]
> Hi,
> The original paper (http://cas.et.tudelft.nl/pubs/Taal2010.pdf) mentions in the start of section 2 that the metric is supposed to be used on audio at a sampling rate of 10000 Hz. Is this really necessary? I get fairly similar results regardless of whether or not I resample my audio.
> 
> Thanks!

pystoi.stoi will resample your input if the sample-rate you input is not 10000.

```
FS = 10000                          # Sampling frequency

...

def stoi(x, y, fs_sig, extended=False):
...

    # Resample is fs_sig is different than fs
    if fs_sig != FS:
        x = utils.resample_oct(x, FS, fs_sig)
        y = utils.resample_oct(y, FS, fs_sig)
...
```

**Comment by anujstam** [comment]
Great! Thanks for clarifying!
