### ISSUE TITLE
Float64 input

### ISSUE THREAD

**Issue by miraodasilva** [mpariente/pystoi#27]
Given the example on the README, I assume pystoi is meant to work with float64 audio (the default format for soundfile.read), but just to be sure, is this indeed the case? Because int16 and int32 are also common encodings and they seem to work fine, but of course don't give the same score as their float64 counterpart. Thanks!

**Comment by mpariente** [comment]
What type of output do you get with integer input?
stoi is meant to work with floats, 32 or 64 shouldn't make a big difference.

**Comment by miraodasilva** [comment]
Thanks for the reply. If I feed integer input (take the float format - scaled between -1 and 1 - multiply it by 2**15 and cast it to int32) I get a reasonable, but generally lower STOI score. Anyway, I will use float from now on as this is what's intended.
