### ISSUE TITLE
The two signals do not match Error 

### ISSUE THREAD

**Issue by Bshbhs** [mpariente/pystoi#29]
Hello, I tried to use STOI to evaluate my speech signals that I get after inserting the data in a simulation room, but the shape is not same for the clean (80000,), noisy (81360,) and the enhanced signals (82959,). Is there any solution to use STOI in that case?

**Comment by mpariente** [comment]
No real scientific solution. Just pad or trim what's needed.

**Comment by Bshbhs** [comment]
Thank you
