### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by gauss256** [mpariente/pystoi#3]
Thanks very much for this code. I found that for Python 3 I had to change the line

    import utils

to

    from . import utils

in `pystoi.py`.

**Comment by mpariente** [comment]
Oh yes I forgot to change this when I made this code a package. Thanks for catching it!
Do you want to submit a PR for this so you get the credit?

**Comment by gauss256** [comment]
Oh right, forgot about capturing the glory. :) OK, I'll do a PR shortly.

**Comment by mpariente** [comment]
Fixed #6
