### ISSUE TITLE
Ability for batched tensor

### ISSUE THREAD

**Issue by MordehayM** [mpariente/pystoi#31]
Thank you for the code!
I have a question: Does this code has the ability to calc the stoi for batched tensor with size of [B, num_of_samples] or even with size of [B, num_speaker, num_of_samples].
I checked and I think it has not this ability, right?
Can you maybe expand the implementaion to this scenario please?

**Comment by mpariente** [comment]
I'm closing the issue as we won't implement any batched computation.
