### ISSUE TITLE
One to two frames are discarded at the end of the signal

### ISSUE THREAD

**Issue by philgzl** [mpariente/pystoi#32]
On two occasions, what seems to be remnants of a faulty MATLAB translation is causing up to 2 frames to be discarded at the end of the signal.

1) In `remove_silent_frames`:
https://github.com/mpariente/pystoi/blob/9ff1cfa743d59b50f1bd35c21c2e8686de6ac026/pystoi/utils.py#L148-L151
The indexing variable should iterate `range(0, len(x) - framelen + 1, hop)` instead. Currently the last frame is discarded if the signal fits an integer number of frames. The corresponding MATLAB line is:
https://github.com/mpariente/pystoi/blob/9ff1cfa743d59b50f1bd35c21c2e8686de6ac026/tests/matlab/removeSilentFrames.m#L6
But in MATLAB the variable can reach the end value as opposed to Python's `range`, so here we need the `+1`.

2) Similarly in `stft`:
https://github.com/mpariente/pystoi/blob/9ff1cfa743d59b50f1bd35c21c2e8686de6ac026/pystoi/utils.py#L98-L99
The indexing variable should iterate `range(0, len(x) - win_size + 1, hop)` for the same reason. The corresponding MATLAB line is:
https://github.com/mpariente/pystoi/blob/9ff1cfa743d59b50f1bd35c21c2e8686de6ac026/tests/matlab/stdft.m#L3

Note that since `remove_silent_frames` removes trailing samples if they do not fit a frame, the subsequent `_overlap_and_add` always produces a signal that fits an integer number of frames. Because of that, `stft` ALWAYS discards one frame! In conclusion, the last two frames are discarded if the signal fits an integer number of frames, else only the last one.

This can be easily verified:
```python
import numpy as np
from pystoi.stoi import stoi

n = 256 + 30*128  # exactly 31 frames
x = np.random.randn(n)
stoi(x, x, 10000)  # raises the RuntimeWarning about not enough frames
```
A breakpoint [here](https://github.com/mpariente/pystoi/blob/9ff1cfa743d59b50f1bd35c21c2e8686de6ac026/pystoi/stoi.py#L61) shows the shape of `x_spec` is `(257, 29)` instead of `(257, 31)`, i.e. two frames are discarded. Fixing the two indexings produces the expected shape.

**Comment by mpariente** [comment]
Thank you very much for the detailed explanation, and the fix for it. 

But pySTOI has been used for years now, and the unit tests to compare to Matlab's STOI were OK, so I won't be accepting the change. 

It does not seem feasible for me to change the source code of a metric that has been used for a long time. I hope you understand.

**Comment by mpariente** [comment]
It is significant, and I appreciate your efforts to debug our indexing mistake. 

I'll give it a bit more thought.

**Comment by mpariente** [comment]
Hey @philgzl,

**Comment by mpariente** [comment]
Sorry, I didn't pay close enough attention to the issue, but actually the indexing was right in the past. `range(0, len(x) - win_size + 1, hop)` is equivalent to this `1:K:(length(x)-N)` because of the starting index. 

I suggest you test against the real Matlab implementation, and if there is a problem we'll fix it.

**Comment by philgzl** [comment]
Indeed, my bad. The last frames are actually also being discarded in the MATLAB implementation.

Example: Signal length 8, frame length 4, hop length 2. Should fit 3 frames, with start indexes [1, 3, 5] in MATLAB. But this MATLAB line returns [1, 3].

![image](https://github.com/mpariente/pystoi/assets/40689706/b5ed9938-a5e6-4917-8df9-eba1fe33d44a)

So I guess we just need to accept this has always been the case.

**Comment by mpariente** [comment]
Thank you very much for your contributions anyway !
